@startuml bluetooth
|用户|
|#AntiqueWhite|App|
start
:调用蓝牙模块
用户可控楼层数组;
|蓝牙模块|
:转发后台;
|#AntiqueWhite|电梯服务器|
:返回可控楼层数组;
|电梯服务器|
:转发蓝牙模块;
|蓝牙模块|
:转发App;
|App|
:展示给用户;
|用户|
:如果用户可以点击并
按下App中的楼层按钮;
|App|
:调用蓝牙模块;
|蓝牙模块|
:转发后台;
|电梯服务器|
:调用电梯控制SDK
发送控制指令;
|电梯控制器|
:控制电梯到选定楼层;
stop
@enduml